### ISSUE TITLE
If "fixed" equals true then the text will not properly hide itself.

### ISSUE THREAD

**Issue by elvisgraho** [TaylorBriggs/react-native-typewriter#17]
**Problem:**

If I add the parameter fixed = true, then the "invisible-string" is not hidden.

**Quick fix**

Change const invisibleStyle = { opacity: 0 } to const invisibleStyle = { opacity: 0, color: 'transparent' } in index.js

**Comment by TaylorBriggs** [comment]
Hi @elvitos-peterson, thanks for letting me know. Feel free to open up a pull request!

**Comment by elvisgraho** [comment]
Actually  invisibleStyle = { color: 'transparent' } just works fine. I don't know if it is the best possible solution considering the fact that the 'transparency' is always performance heavy.

**Comment by TaylorBriggs** [comment]
@elvitos-peterson I just published v0.6.0, which handles hiding the invisible substring a bit differently. Please try it out and let me know how it works for you.

**Comment by TaylorBriggs** [comment]
@elvitos-peterson I'm going to close this for now. Feel free to re-open if you find it's still a problem.
