### ISSUE TITLE
Updating values no longer works

### ISSUE THREAD

**Issue by HorieH** [TaylorBriggs/react-native-typewriter#25]
When I updated the text by clicking the button, it stopped working.
This is my favorite library, so I would like you to fix it if possible.
For specifications, give up and use v0.5.4.

v0.5.4
![sample1](https://user-images.githubusercontent.com/33215452/61776353-cdc12e00-ae35-11e9-89c5-31b4a4f3908b.gif)

v0.6.1
![sample2](https://user-images.githubusercontent.com/33215452/61776358-d1ed4b80-ae35-11e9-910f-33082321b954.gif)

**Comment by TaylorBriggs** [comment]
Can you share a gist or code sample of how you're using the component?

When the button is clicked, does it change the children passed to Typewriter?

One final question, does this bug also exist in v0.6.0?

**Comment by HorieH** [comment]
> Can you share a gist or code sample of how you're using the component?

v0.5.4
https://snack.expo.io/@horieh/typewriterv054

v0.6.0
https://snack.expo.io/@horieh/typewriterv060

> When the button is clicked, does it change the children passed to Typewriter?

Yes

> One final question, does this bug also exist in v0.6.0?

Yes

**Comment by TaylorBriggs** [comment]
Thanks for the demo code, this helps a lot. I think I know what is causing the problem and will try to push a fix this weekend.

**Comment by TaylorBriggs** [comment]
Hi @HorieH, I published [v0.6.2](https://github.com/TaylorBriggs/react-native-typewriter/releases/tag/v0.6.2) which fixes this issue. Please let me know if you try it and the behavior is not what you expect. Thanks!

**Comment by HorieH** [comment]
Perfect.👍 Thank you!
