### ISSUE TITLE
Unhandled JS Exception on fixed={true}

### ISSUE THREAD

**Issue by sobstel** [TaylorBriggs/react-native-typewriter#8]
ERROR: _"Unhandled JS Exception: In this environment the sources for assign MUST be an object.This error is a performance optimization and not spec compliant."_

StyleSheet.create doesn't return a plain javascript object, so the "..." operator sometimes can't be applied. See: https://github.com/TaylorBriggs/react-native-typewriter/blob/master/index.js#L147.

As invisibleStyles are created separately anyway so it might be good to remove "style" from props or to use `StyleSheet.flatten`.

**Original code that doesn't work:**

```
        <TypeWriter
          typing={1}
          minDelay={15}
          maxDelay={60}
          fixed={true}
          style={styles.text}
          onTyped={(token) => this.props.onTyped(token)}
          {...this.props}>
          {text}
        </TypeWriter>
```

```
const styles = EStyleSheet.create({
  text: {
    fontFamily: '$textFont',
    fontSize: responsiveFontSize(2),
    color: '#bbb'
  }
});
```

**Fix/workaround that works**

```
(...)
style={StyleSheet.flatten(styles.text)}
(...)
```

**Comment by TaylorBriggs** [comment]
Sorry for shipping a bug! I believe [this change](https://github.com/TaylorBriggs/react-native-typewriter/pull/9) will fix it by concatenating the styles into an array instead of trying to extend the object.

**Comment by sobstel** [comment]
Thanks for quick feedback! This solves the issue.

**Comment by TaylorBriggs** [comment]
de34410 should fix it. A patch release is coming soon.
